server:
  port: 8888
spring:
  datasource:
    name: db
    url: jdbc:mysql://127.0.0.1:3306/lubov?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: NOT_EMPTY
      db-type: MYSQL
  type-aliases-package: com.i.lubov.entity
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
lubov:
  log:
    enabled: true
  thread-pool:
    core-pool-size: 1
    max-pool-size: 20
    queue-capacity: 100
    keep-alive-seconds: 60
redisson:
  enabled: true
  ttl: 86400000
  maxIdleTime: 86400000
  type: 1
  nodes: redis://127.0.0.1:6379
swagger:
  enabled: true
  title: ilubov
  description: Damon Framework
  version: v5.0.0
generator:
  enabled: true
